name: Release new version of Hazelcast lock server 

on:
  workflow_dispatch:
    inputs: 
    

jobs:
  build_jar:

    runs-on: ubuntu-latest

    steps:
    # Prepare release      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        USERNAME: ${{ github.actor }}    
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name:  ${{ inputs.tag_name }}
        release_name: ${{ inputs.release_name }}
        body: |
          Description of the release
        draft: true
        prerelease: false

    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build with Gradle
      run: ./gradlew build publish
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


